### ISSUE TITLE
How to reload the Nerdtree SVN status icon?

### ISSUE THREAD

**Issue by agentptx** [greggerz/nerdtree-svn-plugin#1]
How to reload the Nerdtree SVN status icon?
The Nerdtree Svn status icon always disappear and how to load it again?

**Comment by greggerz** [comment]
Sorry @agentxpt, i just saw this issue. What platform and version of vim are you using? Is there anything else you can tell me about when the status icons disappear? Is it when you have a large number of changes staged, does it happen after x amount of time, etc.

Does refreshing the filesystem mapping from NERDTree (r or R) bring the status icons back?

**Comment by greggerz** [comment]
I'm going to close this issue; if it's still an issue please reach out to me.
